title: Your Name - UX Research Portfolio
description: UX Researcher & Technical Writer specializing in inclusive educational technology
author: Your Name
email: your.email@example.com

# Build settings
theme: minima
minima:
  skin: classic

# Social media (optional)
github_username: yourusername
linkedin_username: yourprofile

# Header pages
header_pages:
  - index.md

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
